version: '3.0'
services:
  dns:
    image: devries/dnsmasq
    container_name: dnsmasq_container
    #environment:
      #- http_proxy=http://proxy.com:8080
      #- https_proxy=http://proxy.com:8080
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./data/althosts:/etc/althosts
