version: '3'

services:
  backup:
    image: weseek/mongodb-awesome-backup:0.2.0
    environment:
      - CRONMODE=true
      - CRON_EXPRESSION=0 4 * * *                               # change it
      # - AWS_ACCESS_KEY_ID=${Your IAM Access Key ID}           # change it
      # - AWS_SECRET_ACCESS_KEY=${Your IAM Secret Access Key}   # change it
      # - S3_TARGET_BUCKET_URL=s3://${Your Bucket Name}/        # change it
    links:
      - mongo:mongo
    volumes:
      - ./crontab/root:/var/spool/cron/crontabs/root
