version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: apache_container
    #environment:
      #- http_proxy=http://proxy.com:8080
      #- https_proxy=http://proxy.com:8080
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./data/htdocs:/usr/local/apache2/htdocs
      - ./data/conf:/usr/local/apache2/conf
      #- ./data/cgi-bin:/usr/local/apache2/cgi-bin
