FROM  httpd:2.4

#ENV http_proxy http://proxy.com:8080
#ENV https_proxy http://proxy.com:8080

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]
RUN ["apt-get", "install", "-y", "less"]
RUN ["apt-get", "install", "-y", "tcpdump"]
